### ISSUE TITLE
Apple Silicone

### ISSUE THREAD

**Issue by bkervaski** [autozimu/unison-fsmonitor#12]
Hello! We're successfully using unison in fairly high volume with a macOS M1 binary we've compiled.  This is a request to see if you can compile your rust project on an M1 and perhaps update the homebrew release.

If you don't want to, it would be nice to get a copy of the entire rust project so we can give it a go.

Big thanks :)

**Comment by autozimu** [comment]
Hi,

I don't have access to M1 macOS to compile (even if I do, there might be security concerns) and it seems Github Actions doesn't support M1 either https://github.com/actions/virtual-environments/issues/2187

I'd suggest you compile the binaries and fork Hombrew formula repo with the your binary links https://github.com/autozimu/homebrew-formulas/blob/master/Formula/unison-fsmonitor.rb Your users can then use the forked repo to install M1 binaries.

**Comment by diaclavijo** [comment]
@bkervaski Did you finally compiled it? May you share the formula with us? Same problem here.

**Comment by bkervaski** [comment]
I wrote one in node that’s cross platform, then we abandoned unison and built our own sync engine from scratch.  Took about 4 months but it’s awesome.
________________________________

**Comment by d4rky-pl** [comment]
@autozimu could you please reopen this issue and just keep it open? At some point GitHub Actions will support M1 and then it'll be possible to make it work and it'd be nice to have this issue visible until then :)
