### ISSUE TITLE
"Invalid argument: unquote" from lwt.ml, line 126, characters 16-23

### ISSUE THREAD

**Issue by SimonSimCity** [autozimu/unison-fsmonitor#13]
My unison-script is crashing with the following output:

```shell
Looking for changes
Invalid argument: unquote
Raised at Lwt.poll in file "/private/tmp/unison-20211220-29288-1iikm63/unison-2.51.5/src/lwt/lwt.ml", line 126, characters 16-23
Called from Lwt_unix_impl.run in file "/private/tmp/unison-20211220-29288-1iikm63/unison-2.51.5/src/lwt/generic/lwt_unix_impl.ml", line 102, characters 8-23
Called from Uitext.Body.synchronizeOnce in file "/private/tmp/unison-20211220-29288-1iikm63/unison-2.51.5/src/uitext.ml", line 1124, characters 16-56
Called from Uitext.Body.synchronizePathsFromFilesystemWatcher.loop in file "/private/tmp/unison-20211220-29288-1iikm63/unison-2.51.5/src/uitext.ml", line 1183, characters 6-125
Called from Uitext.Body.synchronizeUntilDone in file "/private/tmp/unison-20211220-29288-1iikm63/unison-2.51.5/src/uitext.ml", line 1231, characters 8-47
Called from Uitext.Body.start in file "/private/tmp/unison-20211220-29288-1iikm63/unison-2.51.5/src/uitext.ml", line 1417, characters 21-43
```

More info and a case of how to reproduce can be found at the unison repo: https://github.com/bcpierce00/unison/issues/338#issuecomment-1048562475

According to the maintainers there:
> The '%' character is not percent-encoded and this is what's causing the error.

> I misread the source. Unison does encode the percent character.
> This is a bug in the external fsmonitor.

I'm not that familiar with Rust ... if you would have time to confirm the issue and fix it, I would really appreciate it!

**Comment by autozimu** [comment]
Hi,

Thanks for reporting.

This should have been fixed in https://github.com/autozimu/unison-fsmonitor/commit/c0befde493f9d40eca20e24bdeaa715dad718a0b

Please install the latest 0.3.0 version and let me know if there is still anything.

**Comment by SimonSimCity** [comment]
Thanks, works 🎉
