### ISSUE TITLE
Stale cargo / brew packages

### ISSUE THREAD

**Issue by mc0** [autozimu/unison-fsmonitor#6]
There have been two pretty important bug fixes in the past two weeks[0][1]. This package wasn't usable for me before these fixes and I presume for lots of other people. I was able to build locally and it worked great. Any chance of having new packages published as a new patch version?

Thank you for the great contribution!

0: https://github.com/autozimu/unison-fsmonitor/commit/f37c270c177fbacb980d45c4cf3da46ef7ea2e0a
1: https://github.com/autozimu/unison-fsmonitor/commit/485b6e638f7034205e60c69fe66965c1fe99849d

**Comment by autozimu** [comment]
Thanks for reporting. Will publish a new version shortly.

**Comment by autozimu** [comment]
[0.2.3](https://github.com/autozimu/unison-fsmonitor/commit/840553a72630f6d68e89d5a8f1854bc10fa80c2e) released
