### ISSUE TITLE
Can't sync to my server due to  Filesystem watcher error

### ISSUE THREAD

**Issue by xiaoyuliu** [autozimu/unison-fsmonitor#8]
Hi,

I'm seeing following error
```
Fatal error: Server: Filesystem watcher error: cannot add a watcher: system limit reached
The watcher can be disabled by setting preference 'watch' to false
```

Any suggestion please? Thank you.

**Comment by autozimu** [comment]
You will need to increase the limit of files being watched on the server.

Please follow instructions like https://github.com/guard/listen/wiki/Increasing-the-amount-of-inotify-watchers
